---
- hosts: workstation

  tasks:
    - name: install atom
      mac_pkg: pkg_type=app
               url=https://atom.io/download/mac
               archive_type=zip archive_path='Atom.app'
      sudo: yes
