---
- hosts: workstation

  tasks:
    - name: get oh-my-zsh script
      get_url: url=https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh dest=/tmp/zsh.sh

    - name: change file permission to be executable
      command: chmod +x /tmp/oh-my-zsh.sh

    - name: install zsh
      script: /tmp/oh-my-zsh.sh
