---
- hosts: workstation

  tasks:
    - name: install phpstorm
      mac_pkg: pkg_type=app
               url=https://download.jetbrains.com/webide/PhpStorm-8.0.3.dmg
               archive_type=dmg archive_path='PhpStorm.app'
      sudo: yes
