---
- hosts: workstation

  tasks:
    - name: install SSHFS
      mac_pkg: pkg_name=com.github.osxfuse.pkg.SSHFS pkg_version=2.5.0
               url=https://github.com/osxfuse/sshfs/releases/download/osxfuse-sshfs-2.5.0/sshfs-2.5.0.pkg
      sudo: yes
