---
- hosts: workstation

  tasks:
    - name: install vagrant
      mac_pkg: pkg_name=com.vagrant.vagrant pkg_version=1.7.4
               url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4.dmg
               archive_type=dmg archive_path=Vagrant.pkg
      sudo: yes

